SapMachine #1348: Fix jtreg test jdk/jfr/api/recording/settings/TestGetConfigurations.java
SAP/SapMachine pull request #1349
Opened 2023-02-20 16:06 UTC by ansteiner

Test failed after two additional JFR configuration files were added with https://github.com/SAP/SapMachine/pull/1336

fixes #1348

2023-02-20 16:09 UTC, SapMachine commented
Hello @ansteiner, this pull request fulfills all formal requirements.

2023-02-20 18:22 UTC, RealCLanger requested changes

2023-02-20 18:22 UTC, RealCLanger commented on test/jdk/jdk/jfr/api/recording/settings/TestGetConfigurations.java
> -        Asserts.assertEquals(predefinedConfigs.size(), 2, "Expected exactly two predefined configurations");
Please add a //SapMachine comment here as well

2023-02-20 18:22 UTC, RealCLanger commented on test/jdk/jdk/jfr/api/recording/settings/TestGetConfigurations.java
> +        Configuration gcConfig = findConfigByName(predefinedConfigs, GC_CONFIG_NAME);
Here too.

2023-02-21 08:16 UTC, SapMachine commented
Hello @ansteiner, this pull request fulfills all formal requirements.

2023-02-21 12:35 UTC, ansteiner commented on test/jdk/jdk/jfr/api/recording/settings/TestGetConfigurations.java
> -        Asserts.assertEquals(predefinedConfigs.size(), 2, "Expected exactly two predefined configurations");
done

2023-02-21 12:35 UTC, ansteiner commented on test/jdk/jdk/jfr/api/recording/settings/TestGetConfigurations.java
> +        Configuration gcConfig = findConfigByName(predefinedConfigs, GC_CONFIG_NAME);
done

2023-02-21 12:37 UTC, MBaesken approved these changes

2023-02-21 17:04 UTC, RealCLanger approved these changes
Looks good now. I guess you verified that it fixes the test 😄

2023-02-22 07:26 UTC, merged