SapMachine(11): Compile malloc tracer only for glibc versions < 2.32, and fix tests
SAP/SapMachine pull request #1487
Opened 2023-09-01 08:21 UTC by RealCLanger

We should cherry-pick the change to compile malloc tracer only for glibc versions < 2.32 to SapMachine 11 as well to cater for the upcoming bump to Ubuntu 22 in GHA. I made a few minor modifications to the changelist from SapMachine 17.

fixes #1482

2023-09-01 08:24 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2023-09-01 08:29 UTC, schmelter-sap requested changes
Seems to include an unrelated change

2023-09-01 08:29 UTC, schmelter-sap commented on test/hotspot/jtreg/runtime/malloctrace/MallocTraceTest.java
> +            output.reportDiagnosticSummary();
Shouldn't be related to this change.

2023-09-01 09:49 UTC, ArnoZeller approved these changes
Looks good to me.
I think we should take the not directly related part too. It is useful to get more information in case of an error,

2023-09-01 10:25 UTC, MBaesken approved these changes
Looks okay; I can live with and without the additional reportDiagnosticSummary();

2023-09-04 08:56 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2023-09-04 10:44 UTC, merged