Run wiki update task regularly
SAP/SapMachine pull request #1545
Opened 2023-11-23 06:57 UTC by parttimenerd

fixes #1544

2023-11-23 07:00 UTC, SapMachine commented
Hello @parttimenerd, this pull request fulfills all formal requirements.

2023-11-23 07:11 UTC, RealCLanger requested changes

2023-11-23 07:11 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +      - master
I think the on section is not needed here as the update-wiki action is triggered by the wiki workflow.

2023-11-23 07:11 UTC, RealCLanger commented on .github/workflows/wiki.yml
> +  push:
No reason for on push here, the cron schedule is the thing. However, you could add a "workflow-dispatch" trigger to enable updating manually

2023-11-23 07:17 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +    - uses: actions/checkout@v4
Why is the checkout here necessary? You already do it in the workflow...

2023-11-23 07:52 UTC, parttimenerd commented on .github/actions/update-wiki/action.yml
> +          python3 scripts/update_blogs.py update > ../out
it's in the wiki repo: https://github.com/SAP/SapMachine.wiki.git

2023-11-23 07:55 UTC, parttimenerd commented on .github/actions/update-wiki/action.yml
> +          python3 scripts/update_blogs.py update > ../out
I didn't want to move it too far away from the wiki sources.

2023-11-23 08:05 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +          python3 scripts/update_blogs.py update > ../out
Good. 😄

2023-11-23 08:22 UTC, RealCLanger requested changes
Looks good overall. Some final polishing requested.

2023-11-23 08:22 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +# Runs update-wiki update actions every day at 20:00 UTC
This comment is more appropriate in .github/workflows/wiki.yml

2023-11-23 08:22 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +
Should be: "This action ..."

2023-11-23 08:22 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +          fi
Please also add an output when no updates occured, like:
...
else
    echo "No updates"
...

2023-11-23 08:22 UTC, RealCLanger commented on .github/actions/update-wiki/action.yml
> +      shell: bash
Add line break at the end.

2023-11-23 08:22 UTC, RealCLanger commented on .github/workflows/wiki.yml
> +name: 'Wiki-related'
This is the name we see in the Github Actions. So it should be a bit nicer, like 'Wiki Update'.

2023-11-23 08:22 UTC, RealCLanger commented on .github/workflows/wiki.yml
> +  workflow_dispatch: {}
is the `: {}` needed here?

2023-11-23 08:25 UTC, parttimenerd commented on .github/workflows/wiki.yml
> +  workflow_dispatch: {}
I don't know, YAML is weird

2023-11-23 08:41 UTC, RealCLanger approved these changes

2023-11-23 08:49 UTC, SapMachine commented
Hello @parttimenerd, this pull request fulfills all formal requirements.

2023-11-24 13:02 UTC, MBaesken approved these changes

2023-11-24 13:04 UTC, merged