SapMachine #1693: Support starting child processes in an own process group (unix only)
SAP/SapMachine pull request #1694
Opened 2024-06-12 10:12 UTC by RealCLanger

Add a SapMachine internal API to allow processes started through ProcessBuilder::start to be leader of an own process group instead of belonging to the process group of the parent VM.

Also provide a method to terminate process groups.

fixes #1693

2024-06-12 10:15 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-12 12:36 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-12 18:19 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-13 08:48 UTC, MBaesken requested changes
please look into the typo and look into my comments .

2024-06-13 08:48 UTC, MBaesken commented on make/test/JtregNativeJdk.gmk
> +  #SapMachine 2024-06-12: Eclude libCreateNewProcessGroupOnSpawnTest.c from native compilation on Windows
Eclude - seems to be a little typo

2024-06-13 08:48 UTC, MBaesken commented on src/jdk.sapext/share/classes/module-info.java
> + * Exposes SapMachine only functionality.
Maybe add a line saying what's really in it ? When checking the OpenJDk modules I usually find this info. But not a 'must-have' .

2024-06-13 08:48 UTC, MBaesken commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +        System.loadLibrary(LIB_BASE_NAME);
Should this be some kind of PrivilegedAction ?
check how it is done in the JDK codebase e.g. for
System.loadLibrary("javajpeg");
or
System.loadLibrary("extnet");

But is it not really consistent anyway across the JDK codebase how this is handled ...

2024-06-13 08:48 UTC, MBaesken commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +     * Currently only available on non Windows Platforms.
Maybe better say "on UNIX platforms" (it lives in the unix tree of sources) ?

2024-06-13 08:48 UTC, MBaesken commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +            throw new IOException("Failed to kill process group (" + rc + ")");
according to https://man7.org/linux/man-pages/man2/kill.2.html  rc in the error case is always -1 (but who knows what it is in "real world").
Maybe we could encode the errno in the error case in the ret-value, this might give some insight in case of failures.  But probably more a 'nice to have' ...

2024-06-13 09:12 UTC, schmelter-sap approved these changes
Looks good so far.

2024-06-13 09:12 UTC, schmelter-sap commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    public static final String LIB_BASE_NAME = "sapjdkext";
Doesn't the standalone library currently used has the same name?

2024-06-13 09:12 UTC, schmelter-sap commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    static final void terminateProcessGroupForLeader(Process p, boolean force)
I assume the security depends on getting access to the Process object?

2024-06-21 05:11 UTC, RealCLanger commented on make/test/JtregNativeJdk.gmk
> +  #SapMachine 2024-06-12: Eclude libCreateNewProcessGroupOnSpawnTest.c from native compilation on Windows
Fixed.

2024-06-21 05:51 UTC, RealCLanger commented on src/jdk.sapext/share/classes/module-info.java
> + * Exposes SapMachine only functionality.
I don't want to add more details here because the content can change and such information then tends to become outdated.

2024-06-21 06:04 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +        System.loadLibrary(LIB_BASE_NAME);
Good suggestion. I updated this code.

2024-06-21 06:06 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +     * Currently only available on non Windows Platforms.
I removed this line altogether.

2024-06-21 06:12 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +            throw new IOException("Failed to kill process group (" + rc + ")");
OK, I tried to implement this suggestion. It might help when analyzing problems.

2024-06-21 06:13 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    public static final String LIB_BASE_NAME = "sapjdkext";
Yes, but this implementation should replace the standalone library.

2024-06-21 06:14 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    static final void terminateProcessGroupForLeader(Process p, boolean force)
What do you mean by that? Please help me 😄

2024-06-21 06:17 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-21 06:31 UTC, MBaesken commented on src/jdk.sapext/share/classes/module-info.java
> + * Exposes SapMachine only functionality.
okay fine!

2024-06-21 06:33 UTC, MBaesken approved these changes

2024-06-21 08:06 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-21 08:20 UTC, schmelter-sap commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    static final void terminateProcessGroupForLeader(Process p, boolean force)
To avoid having unauthorized code kill processes.

2024-06-21 08:24 UTC, schmelter-sap commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    public static final String LIB_BASE_NAME = "sapjdkext";
Yes, but if for any reason some might use the old lib with the new VM, we could get hard to debug errors. Using a different name simply avoids this-

2024-06-21 09:03 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    static final void terminateProcessGroupForLeader(Process p, boolean force)
Yes, it goes all through the Process object - so when you are authorized to kill the process, you may do so.

2024-06-21 09:07 UTC, RealCLanger commented on src/jdk.sapext/unix/classes/com/sap/jdk/ext/process/ProcessGroupHelperImpl.java
> +    public static final String LIB_BASE_NAME = "sapjdkext";
OK, maybe err on the safe side. I'll rename it to jdksapext. 😄

2024-06-21 19:25 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-22 09:23 UTC, merged