SapMachine #1670: Improve patch for jcmd GC.heap_dump modification
SAP/SapMachine pull request #1698
Opened 2024-06-19 13:31 UTC by RealCLanger

The SapMachine [commit to modify the jcmd GC.heap_dump](ab72d4e43a708764b3e6a6173e9f2999cf4bc17d) was taken directly from the OpenJDK proposal. In that form, however, it creates a too large upstream diff which could be reduced.

fixes #1670

2024-06-19 13:33 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-19 14:13 UTC, MBaesken requested changes
I think we miss (now?) a couple of // Sapmachine  comments (e.g. heapDumper.cpp).
The globals.hpp change was omitted now; this is okay with me if it is seen better this way (to keep diffs low).

2024-06-19 14:35 UTC, RealCLanger commented
> I think we miss (now?) a couple of // Sapmachine comments (e.g. heapDumper.cpp).
Yes, it was my plan to add them after everything builds and tests are green 😄 

> The globals.hpp change was omitted now; this is okay with me if it is seen better this way (to keep diffs low).
No, it is already in the sapmachine code and won't be rolled back. The actual fix after these modifications can only be seen by diffing all files against openjdk.

2024-06-19 15:46 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-19 17:50 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-19 21:42 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2024-06-20 07:15 UTC, MBaesken approved these changes

2024-06-20 12:35 UTC, schmelter-sap approved these changes
The diff now looks small compared to the version without MBs changes.

2024-06-20 12:40 UTC, merged