Fix file socket transport test on Windows
SAP/SapMachine pull request #1755
Opened 2024-07-13 13:26 UTC by schmelter-sap

This will not run the FileSocketTransportTest on Windows versions which don't support Unix Domain Sockets.

fixes #1690

2024-07-13 13:29 UTC, SapMachine commented
Hello @schmelter-sap, this pull request fulfills all formal requirements.

2024-07-15 08:55 UTC, RealCLanger requested changes

2024-07-15 08:55 UTC, RealCLanger commented on test/jdk/com/sun/jdi/FileSocketTransportTest.java
> +                SocketChannel channel = SocketChannel.open(StandardProtocolFamily.UNIX);
Maybe it's possible to wrap this in a try-with-resources to ensure proper closing of the channel after a successful test?

2024-07-15 12:36 UTC, SapMachine commented
Hello @schmelter-sap, this pull request fulfills all formal requirements.

2024-07-15 12:39 UTC, RealCLanger approved these changes
That looks good. I still found two nits... 😄

2024-07-15 12:39 UTC, RealCLanger commented on test/jdk/com/sun/jdi/FileSocketTransportTest.java
> +                // Windows version is too old to support unix domain sockets.
Maybe a little `System.out.println` trace would be nice here that one can read in the output what happened.

2024-07-15 12:39 UTC, RealCLanger commented on test/jdk/com/sun/jdi/FileSocketTransportTest.java
> +                // Just see if we can create an unix domain socket on Windows.
I think the correct article here is "a". " ... create a unix domain socket ..."

2024-07-16 12:09 UTC, SapMachine commented
Hello @schmelter-sap, this pull request fulfills all formal requirements.

2024-07-16 12:44 UTC, RealCLanger approved these changes

2024-07-16 13:11 UTC, MBaesken approved these changes

2024-07-16 13:12 UTC, MBaesken commented
> This will not run the FileSocketTransportTest on Windows versions which don't support Unix Domain Sockets.

Which Windows version do you thin support it? Is there some minimum version where we expect it to work?

2024-07-19 20:54 UTC, SapMachine commented
Hello @schmelter-sap, this pull request fulfills all formal requirements.

2024-07-23 13:14 UTC, merged