update to sapmachine.io
SAP/SapMachine pull request #1768
Opened 2024-07-29 15:37 UTC by skateball

compare #5385

2024-07-29 15:40 UTC, SapMachine commented
Hello @skateball, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

2024-07-29 15:55 UTC, SapMachine commented
Hello @skateball, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

2024-07-30 08:53 UTC, RealCLanger requested changes
There are a few files contained in this PR which we should not add.

2024-07-30 08:53 UTC, RealCLanger commented on index.md
> +
Please remove  the ToDos

2024-08-21 13:46 UTC, closed without merging