Fix some tools tests after adding asprof
SAP/SapMachine pull request #1841
Opened 2024-10-07 14:01 UTC by MBaesken

The description of this pull request goes here.

fixes #1823  
this broke some tests that check command line options of tools, but asprof is unknown to these tests

2024-10-07 14:04 UTC, SapMachine commented
Hello @MBaesken, I'm sorry, this pull request doesn't meet the expectations. The pull request description has an invalid format. Please have a look at https://github.com/SAP/SapMachine/wiki/Formal-Requirements-of-Pull-Requests .

2024-10-07 14:13 UTC, SapMachine commented
Hello @MBaesken, this pull request fulfills all formal requirements.

2024-10-07 14:41 UTC, RealCLanger requested changes
I made a few suggestions. Other than that, when the tests are green, I guess it's fine. 😄

2024-10-07 14:41 UTC, RealCLanger commented on test/jdk/TEST.groups
> +# SapMachine 2024-10-07: asprof was added on some platforms but has different command line flags; affects tools/launcher
The new comment line is not necessary, I think.

2024-10-07 14:41 UTC, RealCLanger commented on test/jdk/TEST.groups
> +    tools/launcher/HelpFlagsTest.java \
could you sort the tests alphabetically?

2024-10-07 14:41 UTC, RealCLanger commented on test/jdk/tools/launcher/VersionCheck.java
> +    // SapMachine 2024-10-07: asprof was added on some platforms but has different command line flags
rather place the comment above asprof below

2024-10-07 14:41 UTC, RealCLanger commented on test/jdk/tools/launcher/VersionCheck.java
> +        "asprof"
add a SapMachine comment here as well

2024-10-07 16:28 UTC, SapMachine commented
Hello @MBaesken, this pull request fulfills all formal requirements.

2024-10-08 07:25 UTC, RealCLanger approved these changes

2024-10-08 07:47 UTC, ansteiner approved these changes
LGTM

2024-10-08 08:38 UTC, merged