SapMachine (16) #820: Bring Vitals up to date
SAP/SapMachine pull request #892
Opened 2021-07-12 21:09 UTC by RealCLanger

Cherry-Pick Vitals update to sapmachine 16

fixes #820

2021-07-12 21:11 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2021-07-13 03:44 UTC, tstuefe approved these changes

2021-07-13 04:07 UTC, tstuefe requested changes
Hi Christioph,

thanks for doing this. Ignore my earlier approval, this needs some fixes to build with 16:

```
--- a/src/hotspot/share/vitals/vitals.cpp
+++ b/src/hotspot/share/vitals/vitals.cpp
@@ -25,7 +25,7 @@
  */
 
 #include "precompiled.hpp"
-#include "jvm_io.h"
+#include "jvm.h"
 
 #include "gc/shared/collectedHeap.hpp"
 #include "classfile/classLoaderDataGraph.inline.hpp"
@@ -35,7 +35,6 @@
 #include "runtime/os.hpp"
 #include "runtime/mutex.hpp"
 #include "runtime/mutexLocker.hpp"
-#include "runtime/nonJavaThread.hpp"
 #include "runtime/thread.hpp"
 #include "services/memTracker.hpp"
 #include "services/mallocTracker.hpp"
```

(or, apply my suggestions.)

Cheers, Thomas

2021-07-13 04:07 UTC, tstuefe commented on src/hotspot/share/vitals/vitals.cpp
> +#include "jvm_io.h"
```suggestion
#include "jvm.h"
```

2021-07-13 04:07 UTC, tstuefe commented on src/hotspot/share/vitals/vitals.cpp
> +#include "runtime/nonJavaThread.hpp"
Remove that line

```suggestion
```

2021-07-13 04:26 UTC, RealCLanger commented
> Hi Christioph,
> 
> thanks for doing this. Ignore my earlier approval, this needs some fixes to build with 16:
> 

Thanks, Thomas. I updated the change with your suggestions.

2021-07-13 04:27 UTC, SapMachine commented
Hello @RealCLanger, this pull request fulfills all formal requirements.

2021-07-13 04:43 UTC, tstuefe approved these changes
All good now. Thanks!

2021-07-13 08:30 UTC, schmelter-sap approved these changes
LGTM

2021-07-13 09:14 UTC, merged